# Generated by Django 3.2.11 on 2022-10-20 22:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0031_alter_severity_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraReportContextType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for this field to be used inside report templates (formatted like a slug)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='This identifier can only be made up of lowercase letters, numbers, and hyphens.', regex='^[a-z0-9]+(?:-[a-z0-9]+)*$')])),
                ('title', models.CharField(help_text='Provide a descriptive title for this section that can also be used in a report template', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Provide a description for this section (e.g., how it should be used, why it was created)', null=True, verbose_name='Description')),
                ('default', models.BooleanField(default=False, help_text='Check this box if this section should be included in all reports by default', verbose_name='Default')),
                ('protected', models.BooleanField(default=False, help_text='Make it so only administrators and managers can edit this section configuration', verbose_name='Protected')),
                ('content_type', models.CharField(choices=[('richtext', 'RichText Section'), ('variable', 'Text Variable'), ('boolean', 'Boolean Variable'), ('json', 'JSON Blob')], default='richtext', help_text='Select the type of value you want to create', max_length=8, verbose_name='Content Type')),
                ('default_variable', models.CharField(blank=True, help_text='Set the default content for a report variable', max_length=255, null=True, verbose_name='Default Value')),
                ('default_boolean', models.BooleanField(default=False, help_text='Set the default value for a boolean variable', verbose_name='Default Value')),
                ('default_richtext', models.TextField(blank=True, help_text='Provide default content for a RichText section', null=True, verbose_name='Default Content')),
                ('default_json', models.JSONField(blank=True, help_text='Provide default content for a JSON blob', null=True, verbose_name='Default Content')),
            ],
            options={
                'verbose_name': 'Report section',
                'verbose_name_plural': 'Report sections',
                'ordering': ['content_type', 'title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExtraReportContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_content', models.CharField(blank=True, help_text='Set the content for this report variable', max_length=255, null=True, verbose_name='Content')),
                ('boolean_value', models.BooleanField(default=False, help_text='Set the value for this boolean variable', verbose_name='Value')),
                ('richtext_content', models.TextField(blank=True, help_text='Provide the content for this report section', null=True, verbose_name='Content')),
                ('json_content', models.JSONField(blank=True, help_text='Provide the JSON content this report variable', null=True, verbose_name='Default Content')),
                ('context_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.extrareportcontexttype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.report')),
            ],
            options={
                'verbose_name': 'Extra report context',
                'verbose_name_plural': 'Extra report context',
                'ordering': ['report', 'context_type__content_type', 'context_type__name'],
                'unique_together': {('report', 'context_type')},
            },
        ),
    ]
