# Generated by Django 3.2.11 on 2022-10-31 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0032_extrareportcontext_extrareportcontexttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrareportcontexttype',
            options={'ordering': ['content_type', 'title', 'name'], 'verbose_name': 'Extra report context type', 'verbose_name_plural': 'Extra report context type'},
        ),
        migrations.AlterField(
            model_name='extrareportcontexttype',
            name='name',
            field=models.CharField(help_text='Unique identifier for this field to be used inside report templates (formatted like a slug)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='This identifier can only be made up of lowercase letters, numbers, underscores, and hyphens.', regex='^[a-z0-9]+(?:[a-z0-9_-]+)*$')]),
        ),
    ]
